import { useState } from 'react'
import { api } from './api'
import './auth.css'

export default function Auth({ onAuthenticated }) {
  const [mode,setMode]=useState('login'), [form,setForm]=useState({name:'',email:'',password:'',role:'STAFF',adminKey:''}), [error,setError]=useState(''), [loading,setLoading]=useState(false)
  const update=(k,v)=>setForm(x=>({...x,[k]:v}))
  async function submit(e){e.preventDefault();setError('');setLoading(true);try{const r=mode==='login'?await api.login(form):await api.register(form);localStorage.setItem('living_bells_token',r.token);localStorage.setItem('living_bells_user',JSON.stringify(r.user));onAuthenticated(r.user)}catch(err){setError(err.message)}finally{setLoading(false)}}
  return <main className="auth-shell"><section className="auth-card"><div className="auth-brand"><span>L</span><div><b>Living Bells</b><small>Church operations</small></div></div><span className="eyebrow">Staff workspace</span><h1>{mode==='login'?'Welcome back':'Create your staff account'}</h1><p className="auth-subtitle">{mode==='login'?'Sign in to manage church activities, attendance and expenses.':'Choose Staff or Admin for this church workspace.'}</p>{error&&<div className="auth-error">{error}</div>}<form onSubmit={submit}>{mode==='register'&&<label>Full name<input value={form.name} onChange={e=>update('name',e.target.value)} required /></label>}<label>Email<input type="email" value={form.email} onChange={e=>update('email',e.target.value)} required /></label><label>Password<input type="password" minLength="8" value={form.password} onChange={e=>update('password',e.target.value)} required /></label>{mode==='register'&&<label>Account type<select value={form.role} onChange={e=>update('role',e.target.value)}><option value="STAFF">Staff</option><option value="ADMIN">Admin</option></select></label>}{mode==='register'&&form.role==='ADMIN'&&<label>Admin registration key<input type="password" value={form.adminKey} onChange={e=>update('adminKey',e.target.value)} required /></label>}<button className="primary auth-submit" disabled={loading}>{loading?'Please wait...':mode==='login'?'Sign in':'Create account'}</button></form><div className="auth-switch">{mode==='login'?<>New staff member? <button onClick={()=>setMode('register')}>Create an account</button></>:<>Already registered? <button onClick={()=>setMode('login')}>Sign in</button></>}</div></section></main>
}